"""implement image name to listing

Revision ID: 74fd0c859834
Revises: 81ed027955aa
Create Date: 2025-03-13 18:12:08.838279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74fd0c859834'
down_revision = '81ed027955aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listing_images_id', table_name='listing_images')
    op.drop_table('listing_images')
    op.add_column('listings', sa.Column('image_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'image_name')
    op.create_table('listing_images',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('listing_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['categories.id'], name='listing_images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_listing_images_id', 'listing_images', ['id'], unique=True)
    # ### end Alembic commands ###
