"""update address to text

Revision ID: f9a731e97abb
Revises: 74fd0c859834
Create Date: 2025-03-18 14:54:08.207008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9a731e97abb'
down_revision = '74fd0c859834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=80),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'address',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
